[pytest]
asyncio_mode = auto
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
;env =
;    POSTGRES_USER=test
;    POSTGRES_PASSWORD=test
;    POSTGRES_HOST=localhost
;    POSTGRES_PORT=5432
;    POSTGRES_DB=test_db
;    DATABASE_URL=sqlite+aiosqlite:///:memory: